"use client"

import Head from "next/head"
import { Inter } from "next/font/google"
import { Canvas, useFrame } from "@react-three/fiber"
import { Model } from "@/public/Ferrari"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ferrari</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Canvas>
        <ambientLight />
        <directionalLight />
        <pointLight position={[-4, 4, 6]} />
        <pointLight position={[0, 2, 2]} />
        <Model rotation={[0.4, 1.2, 0]} scale={1.25} />
      </Canvas>
    </>
  )
}
